# User config
author: "WORKERS LIFE"
tagline: "Pineapple Certfied Jekyll Theme"
description: "Designing solves everything"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "japhodbblebrox@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
url: "https://japhodbblebrox.github.io"
baseurl: " "
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed